DROP DATABASE IF EXISTS LSG_Bars;

CREATE DATABASE IF NOT EXISTS LSG_Bars
DEFAULT CHARSET 'utf8mb4'
DEFAULT COLLATE 'utf8mb4_spanish_ci';

USE LSG_Bars;

-- Creación de tablas

DROP TABLE IF EXISTS Tapa;
CREATE TABLE IF NOT EXISTS Tapa(
	IDTapa INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(30) DEFAULT '',
    DescripcioCarta VARCHAR(30) DEFAULT '',
    TempsPreparacio INT,
    EsCalent BOOL,
    EsVegeta BOOL,
    EsIndividual BOOL,
    CONSTRAINT PK_Tapa PRIMARY KEY (IDTapa)
);

DROP TABLE IF EXISTS Distribuidor;
CREATE TABLE IF NOT EXISTS Distribuidor(
	IDDistribuidor INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NomEmpresa VARCHAR(30) DEFAULT '',
    ContactePrincipal VARCHAR(30) DEFAULT '',
    Telefon INT,
    Email NVARCHAR(30),
    Web VARCHAR(30),
    CONSTRAINT PK_Distribuidor PRIMARY KEY (IDDistribuidor)
);

DROP TABLE IF EXISTS Ingredient;
CREATE TABLE IF NOT EXISTS Ingredient(
	IDIngredient INT UNSIGNED NOT NULL,
    Nom VARCHAR(30) DEFAULT '',
    Descripcio VARCHAR(30) DEFAULT '',
    EsPicant BOOL,
    EsImportacio BOOL,
    CostGram FLOAT,
    IDDistribuidor INT UNSIGNED AUTO_INCREMENT,
    CONSTRAINT PK_Ingredient PRIMARY KEY (IDIngredient),
    CONSTRAINT FK_Ingredient_Distribuidor FOREIGN KEY (IDDistribuidor) REFERENCES Distribuidor (IDDistribuidor)
);

DROP TABLE IF EXISTS Beguda;
CREATE TABLE IF NOT EXISTS Beguda(
	IDBeguda INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(30) DEFAULT '',
    Descripcio VARCHAR(30) DEFAULT '',
    EsCalent BOOL,
    TeAlcohol BOOL,
    QuanitatCL INT,
    CONSTRAINT PK_Beguda PRIMARY KEY (IDBeguda)
);

DROP TABLE IF EXISTS Distro_Beguda;
CREATE TABLE IF NOT EXISTS Distro_Beguda(
	IDDistribuidor INT UNSIGNED NOT NULL,
    IDBeguda INT UNSIGNED NOT NULL,
    CostVenda DECIMAL(8,2),
    CONSTRAINT PK_Distro_Beguda PRIMARY KEY (IDDistribuidor, IDBeguda),
    CONSTRAINT FK_DB_Distro FOREIGN KEY (IDDistribuidor) REFERENCES Distribuidor (IDDistribuidor) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DB_Beguda FOREIGN KEY (IDBeguda) REFERENCES Beguda (IDBeguda) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Ingredients_Tapa;
CREATE TABLE IF NOT EXISTS Ingredients_Tapa(
	IDIngredient INT UNSIGNED NOT NULL,
    IDTapa INT UNSIGNED NOT NULL,
    Quantitat INT,
    CONSTRAINT PK_Ingredients_Tapa PRIMARY KEY (IDIngredient, IDTapa),
    CONSTRAINT FK_IT_Ingredient FOREIGN KEY (IDIngredient) REFERENCES Ingredient (IDIngredient) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_IT_Tapa FOREIGN KEY (IDTapa) REFERENCES Tapa (IDTapa) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Localitat;
CREATE TABLE IF NOT EXISTS Localitat (
	IDLloc INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NomLocalitat VARCHAR(30) DEFAULT '',
	Provincia VARCHAR(30) DEFAULT '',
	ComunitatAutonoma VARCHAR(30) DEFAULT '',
	Pais VARCHAR(30) DEFAULT '',
	Continent VARCHAR(30) DEFAULT '',
	CONSTRAINT PK_Localitat PRIMARY KEY (IDLloc)
);

DROP TABLE IF EXISTS Bar;
CREATE TABLE IF NOT EXISTS Bar(
	IDBar INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(30),
    AforamentMaxim INT,
    TeExterior BOOL,
    Ubicacio INT UNSIGNED NOT NULL,
    CONSTRAINT PK_Bar PRIMARY KEY (IDBar),
    CONSTRAINT FK_Bar_Localitat FOREIGN KEY (Ubicacio) REFERENCES Localitat (IDLloc) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Taula;
CREATE TABLE IF NOT EXISTS Taula(
	NumeroTaula INT NOT NULL AUTO_INCREMENT,
    IDBar INT UNSIGNED NOT NULL,
    EsExterior BOOL,
    EsFumadors BOOL,
    NumCadires INT,
    CONSTRAINT PK_Taula PRIMARY KEY (NumeroTaula, IDBar),
    CONSTRAINT FK_Taula_Bar FOREIGN KEY (IDBar) REFERENCES Bar (IDBar) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Carta_Begudes;
CREATE TABLE IF NOT EXISTS Carta_Begudes(
	IDBeguda INT UNSIGNED NOT NULL,
    IDBar INT UNSIGNED NOT NULL,
    Cost DECIMAL(8,2),
    PVP DECIMAL(8,2),
    CONSTRAINT PK_Carta_Begudes PRIMARY KEY (IDBeguda, IDBar),
    CONSTRAINT FK_CB_Beguda FOREIGN KEY (IDBeguda) REFERENCES Beguda (IDBeguda) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_CB_Bar FOREIGN KEY (IDBar) REFERENCES Bar (IDBar) ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS Carta_Tapes;
CREATE TABLE IF NOT EXISTS Carta_Tapes(
	IdTapa INT UNSIGNED NOT NULL,
    IdBar INT UNSIGNED NOT NULL,
    Cost DECIMAL(8,2),
    PVP DECIMAL(8,2),
    CONSTRAINT PK_Carta_Tapes PRIMARY KEY (IdTapa, IdBar),
    CONSTRAINT FK_CT_Tapa FOREIGN KEY (IdTapa) REFERENCES Tapa (IdTapa) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_CT_Bar FOREIGN KEY (IdBar) REFERENCES Bar (IdBar) ON DELETE RESTRICT ON UPDATE RESTRICT
);

DROP TABLE IF EXISTS Persona;
CREATE TABLE IF NOT EXISTS Persona (
	DNI VARCHAR(9) NOT NULL,
	Nom VARCHAR(30) NOT NULL DEFAULT '',
	Cognom1 VARCHAR(30) NOT NULL DEFAULT '',
	Cognom2 VARCHAR(30) NOT NULL DEFAULT '',
	Email NVARCHAR(30) NOT NULL,
	CONSTRAINT UC_Persona UNIQUE (Email),
	CONSTRAINT PK_Persona PRIMARY KEY (DNI)
);

DROP TABLE IF EXISTS `Client`;
CREATE TABLE IF NOT EXISTS `Client` (
	DNIClient VARCHAR(9) NOT NULL,
	EsMajor BOOL NOT NULL,
	CONSTRAINT PK_Client PRIMARY KEY (DNIClient),
	CONSTRAINT FK_Client FOREIGN KEY (DNIClient) REFERENCES Persona (DNI) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS Client_Taula;
CREATE TABLE IF NOT EXISTS Client_Taula(
	IdClientTaula INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DNIClient VARCHAR(9) NOT NULL,
    NumeroTaula INT NOT NULL,
    IdBar INT UNSIGNED NOT NULL,
    EsFumador BOOL DEFAULT FALSE,
    DataHoraArribada DATETIME,
    DataHoraSortida DATETIME,
    HaPagat BOOL,
    CONSTRAINT PK_Client_Taula PRIMARY KEY (IdClientTaula),
    CONSTRAINT FK_CT_Client FOREIGN KEY (DNIClient) REFERENCES `Client` (DNIClient) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CT_Taula FOREIGN KEY (NumeroTaula, IdBar) REFERENCES Taula (NumeroTaula, IdBar) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Comanda_Begudes;
CREATE TABLE IF NOT EXISTS Comanda_Begudes(
	IdBeguda INT UNSIGNED NOT NULL,
    IdBar INT UNSIGNED NOT NULL,
    IdClientTaula INT UNSIGNED NOT NULL,
    DataHoraComanda DATETIME,
    Quantitat INT,
    CONSTRAINT PK_Comanda_Begudes PRIMARY KEY (IdBeguda, IdBar, IdClientTaula),
    CONSTRAINT FK_CB_1 FOREIGN KEY (IdBeguda) REFERENCES Beguda (IdBeguda) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CB_CartaB FOREIGN KEY (IdBar) REFERENCES Bar (IdBar) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CB_CT FOREIGN KEY (IdClientTaula) REFERENCES Client_Taula (IdClientTaula) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Comanda_Tapes;
CREATE TABLE IF NOT EXISTS Comanda_Tapes(
	IdTapa INT UNSIGNED NOT NULL,
    IdBar INT UNSIGNED NOT NULL,
    IdClientTaula INT UNSIGNED NOT NULL,
    DataHoraComanda DATETIME,
    Quantitat INT,
    CONSTRAINT PK_Comanda_Tapes PRIMARY KEY (IdTapa, IdBar, IdClientTaula),
    CONSTRAINT FK_CT_CartaT FOREIGN KEY (IdTapa, IdBar) REFERENCES Carta_Tapes (IdTapa, IdBar) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CT_ClientT FOREIGN KEY (IdClientTaula) REFERENCES Client_Taula (IdClientTaula) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Carrec_Empleat;
CREATE TABLE IF NOT EXISTS Carrec_Empleat (
	NomCarrec VARCHAR(30) NOT NULL,
	Descripcio VARCHAR(30),
	HoresContracte INT NOT NULL,
	SouBase DECIMAL(8,2),
	CONSTRAINT PK_Carrec_empleat PRIMARY KEY (NomCarrec)
);


DROP TABLE IF EXISTS Empleat;
CREATE TABLE IF NOT EXISTS Empleat (
	DNIEmpleat VARCHAR(9) NOT NULL,
	NumSS VARCHAR(12),
	NumCC VARCHAR(24) NOT NULL,
	QuantititatSouExtra DECIMAL(8,2) NOT NULL,
	NomCarrec VARCHAR(30) NOT NULL,
	DNICap VARCHAR(9) NOT NULL,
	LlocNeixament INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT PK_Empleat PRIMARY KEY (DNIEmpleat),
	CONSTRAINT FK_Empleat_Persona FOREIGN KEY (DNIEmpleat) REFERENCES Persona (DNI),
	CONSTRAINT FK_Empleat_Carrec FOREIGN KEY (NomCarrec) REFERENCES Carrec_Empleat (NomCarrec) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_Empleat_Empleat FOREIGN KEY (DNICap) REFERENCES Empleat (DNIEmpleat) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_Empleat_Localitat FOREIGN KEY (LlocNeixament) REFERENCES Localitat (IDLloc) ON DELETE CASCADE ON UPDATE CASCADE
);






